version: '3'
services:
  apache_php74:
    container_name: apache_php74
    restart: always
    build: .
    environment:
      TZ: America/Brasilia
    ports: 
      - 9090:80
    volumes:
      - ./users_data:/var/www/html
    depends_on:
      - database

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    mem_limit: 128m
    memswap_limit: 0
    mem_swappiness: 0
    restart: always
    depends_on:
      - database
    ports:
      - 8282:80
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=root

  database:
     container_name: database
     image: mariadb:10.1.30
     restart: always
     volumes:
       - ./mysql-data-database:/var/lib/mysql
     ports:
       - 3406:3306
     mem_limit: 8192m
     memswap_limit: 0
     mem_swappiness: 0
     restart: always
     environment:
      - MYSQL_ROOT_PASSWORD=mockroot
      - MYSQL_USER=eulr
      - MYSQL_PASSWORD=mockpass
      - TZ=America/Brasilia
     volumes:
       - ./mariaDb/conf.d:/etc/mysql/conf.d